hwdec=auto

save-position-on-quit=true

autofit=80%

sub-auto=fuzzy

slang=en

# on screen controller
osc=no
osd-bar=no
# Hide the controls automatically after 1 second of mouse inactivity
script-opts=osc-hidetimeout=1000
