# touchpad
input "type:touchpad" {
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
    dwt enabled
    
    # Increase tracking speed (0.0 is default, 1.0 is max speed)
    pointer_accel 0.4
}
