# touchpad
input "type:touchpad" {
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
    dwt enabled
    
    #Use 'flat' for predictable, raw 1:1 tracking (removes weird acceleration jumps)
    accel_profile flat
    
    # Increase tracking speed (0.0 is default, 1.0 is max speed)
    pointer_accel 0.7

    # Fine-tune scroll speed if two-finger scrolling feels too fast or sluggish
    scroll_factor 0.7

    # Disable drag lock so lifting you finger instantly unselects text
    drag_lock disabled
}
