[main]

term=foot
title=foot
locked-title=no
 
font=ZedMono Nerd Font Mono:size=16

pad=8x8

dpi-aware=yes

bold-text-in-bright=yes

initial-window-size-pixels = 1200x800

[csd]
preferred=none

# [cursor]
#style=block
#blink=no
#blink-rate=500
#beam-thickness=1.5
#underline-thickness=<font underline thickness>

[colors-dark]
alpha=1
background=1e1e2e
foreground=dcdcdc
cursor=dcdcdc 7aa2f7

# black
regular0 = 1e1e2e
bright0  = 7a7a89

# red
regular1 = f7768e
bright1  = ff6e7f

# green
regular2 = 9ece6a
bright2  = c0fca0

# yellow
regular3 = e0af68
bright3  = f9e2af

# blue
regular4 = 7aa2f7
bright4  = 89b4fa

# magenta
regular5 = bb9af7
bright5  = cba6f7

# cyan
regular6 = 7dcfff
bright6  = 94e2d5

# white
regular7 = c0c0c0
bright7  = f4f4f5
